name: Generate Pacman Animation

on:
  schedule:
    - cron: "0 */6 * * *"  # Executa a cada 6 horas
  workflow_dispatch:       # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Pacman SVG
        uses: Platane/snk@v3
        with:
          github_user_name: joaodevtech   # <-- coloque seu usuÃ¡rio aqui
          outputs: |
            dist/pacman.svg

      - name: Deploy to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
          force_orphan: true
